### ISSUE TITLE
Constant values for enumSource broken

### ISSUE THREAD

**Issue by mbrodala** [jdorn/json-editor#432]
The following schema is supposed to produce an select field with two constant values to chose from:

```json
{
  "type": "string",
  "enumSource": [
    ["foo"],
    ["bar"]
  ]
}
```

However, the following [error is thrown](http://jeremydorn.com/json-editor/?schema=N4IgLgngDgpiBcID2AjAVjAxmEAaEUATkrIWAJYwDOCoKAhobeNHIlWIeQHYDmeIGNwCuAWwDKSYYUxsA2qCpSZ8gLoBfDevVAA=&value=N4IgRghgTiBcIgL5AAA=&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction) instead:

> Uncaught TypeError: a.match is not a function

The error is apparently thrown in the [`compile` method of the template engine](https://github.com/jdorn/json-editor/blob/92857220697d0e4265a1945b9a469962c340921e/dist/jsoneditor.js#L6818).

**Comment by abloomston** [comment]
In my environment, this commit looks to be the culprit: 446f2e46e45a4e560db70d65d48895be549b890d

**Comment by mbrodala** [comment]
@jdorn Could you have a look at this?

**Comment by abe1001** [comment]
I'm also having a problem with this. My pages for user editing has stopped working :-\

**Comment by simevo** [comment]
Same here. Reverting the commit ```446f2e4``` as mentioned by @abloomston also fixed the matter for me.

**Comment by tokland** [comment]
Thanks @abloomston, reverting this commit works as a temporary fix. I'd expect ```{"value": "constant"}``` also to work, but it does not.  @mbrodala you can join those elements: ```"enumSource": [["foo", "bar], ...]```

**Comment by mbrodala** [comment]
@tokland You mean when reverting the commit in question? Otherwise the error is the same.

**Comment by tokland** [comment]
@mbrodale: yes, no way around that.

**Comment by svendhhh** [comment]
Isn't anyone able to fix this, if it's narrowed down to just one (fairly small) commit?
Otherwise wouldn't it be worth considering reverting the commit alltogether (if it's only a speed-up commit (I don't know if the speedup would be so significant that reverting isn't an option))?

**Comment by jeremyjannotta** [comment]
+1
We are getting this error too, which is particularly an issue since support for the constant syntax is still in the documentation while it's broken.

**Comment by svendhhh** [comment]
We've managed to work around the bug by defining the constant as an enumsource as well, with just one static value as source:

```json
"object": {
	"watch": {
		"ids": "somename.someIds"
	},
	"enumSource": [
		{
			"source": [
				{
					"value": "None"
				}
			],
			"title": "{{item.value}}",
			"value": "{{item.value}}"
		},
		{
			"source": "ids",
			"title": "{{item.id}}",
			"value": "{{item.id}}"
		}
	]
}
```
